name: qbittorrent with ProtonVPN P2P

services:
  qbittorrent:
    image: linuxserver/qbittorrent:${QBITTORRENT_VERSION}
    container_name: qbittorrent
    depends_on:
      - protonvpn
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - qbittorrent_appdata:/config:wr
      - ~/Downloads:/data/downloads:wr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ
      - WEBUI_PORT=8083
      - TORRENTING_PORT=6881
    ports:
      - '0.0.0.0:6881:6881'
      - '0.0.0.0:6881:6881/udp'
      - '127.0.0.1:8083:8083'
    network_mode: "service:protonvpn"
    restart: unless-stopped
    labels:
      - wud.tag.include=^\d\.\d+\.\d+$$
      - traefik.enable=true
      - traefik.http.routers.qbittorrent-qbittorrent.rule=Host(`qb.dhjensen.tech`)
      - traefik.http.services.qbittorrent-qbittorrent.Loadbalancer.server.port=8083

  protonvpn:
    image: qmcgaw/gluetun:v${GLUETUN_VERSION}
    container_name: vpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun:ro
    entrypoint:
      - TZ
      - VPN_SERVICE_PROVIDER
      - VPN_TYPE
      - VPN_PORT_FORWARDING
      - SERVER_COUNTRIES
      - PORT_FORWARD_ONLY=on
      - VPN_PORT_FORWARDING_UP_COMMAND=/bin/sh -c '/usr/bin/wget -O- --retry-connrefused --post-data "json={\"listen_port\":{{PORTS}}}" http://127.0.0.1:8083/api/v2/app/setPreferences 2>&1'
    volumes:
      - ./vpn:/gluetun:ro
    ports:
      - '127.0.0.1:8083:8083'
    restart: unless-stopped
    labels:
      - wud.tag.include=^\d\.\d+\.\d+$$
      - traefik.enable=false  

networks:
  backend:
    driver: bridge
    external: true

volumes:
  qbittorrent_appdata:
