name: qbittorrent with ProtonVPN P2P

services:
  gluetun:
    image: qmcgaw/gluetun:v${GLUETUN_VERSION}
    container_name: vpn
    volumes:
      - gluetun-config:/gluetun:rw
    ports:
      - '127.0.0.1:8083:8083'
    environment:
      - VPN_SERVICE_PROVIDER
      - VPN_TYPE
      - WIREGUARD_PRIVATE_KEY
      - SERVER_COUNTRIES
      - PORT_FORWARD_ONLY=on
      - VPN_PORT_FORWARDING
      - TZ
      - QBT_WEBUI_ENABLED=true
    networks:
      - backend
    restart: unless-stopped
    labels:
      - wud.tag.include=^v\d\.\d+\.\d+$$
      - traefik.enable=true
      - traefik.http.routers.gluetun-qbittorrentwithprotonvpnp2p.rule=Host(`qb.dhjensen.tech`)
      - traefik.http.services.gluetun-qbittorrentwithprotonvpnp2p.Loadbalancer.server.port=8083
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun:rw

  qbittorrent:
    image: linuxserver/qbittorrent:${QBITTORRENT_VERSION}
    container_name: qbittorrent
    depends_on:
      gluetun:
        condition: service_healthy
    volumes:
      - qbittorrent-appdata:/config:rw
      - ~/Downloads:/data/downloads:rw
    environment:
      - PUID=1000
      - PGID=1000
      - TZ
      - WEBUI_PORT=8083
      - QBITTORRENT_INTERFACE=tun0
      - DOCKER_MODS=ghcr.io/t-anc/gsp-qbittorent-gluetun-sync-port-mod:main
      - GSP_GTN_API_KEY=${GSP_GTN_API_KEY:-randomapikey}
      - GSP_QBITTORRENT_PORT=${GSP_QBITTORRENT_PORT:-53764}
    network_mode: "service:gluetun"
    restart: unless-stopped
    labels:
      - wud.tag.include=^\d\.\d+\.\d+$$
      - traefik.enable=false
    ulimits:
      nofile:
        soft: 32768
        hard: 65536

networks:
  backend:
    driver: bridge
    external: true

volumes:
  gluetun-config:
  qbittorrent-appdata:
